// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRycVf3kYqyZt_VMiWDkGXJss_ypYj-GY',
    appId: '1:168903104893:web:927998f08320fc357ed414',
    messagingSenderId: '168903104893',
    projectId: 'dietaiapp-268dd',
    authDomain: 'dietaiapp-268dd.firebaseapp.com',
    storageBucket: 'dietaiapp-268dd.firebasestorage.app',
    measurementId: 'G-328ZLHGVGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOtAvxdkgQGxoHeTF5gokTEM-a6x-WDsY',
    appId: '1:168903104893:android:f675d1becfbfd4717ed414',
    messagingSenderId: '168903104893',
    projectId: 'dietaiapp-268dd',
    storageBucket: 'dietaiapp-268dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInfrJGZc5t9uQ9yV9S3MnjHvZdoOU4zU',
    appId: '1:168903104893:ios:e0009959c9e332487ed414',
    messagingSenderId: '168903104893',
    projectId: 'dietaiapp-268dd',
    storageBucket: 'dietaiapp-268dd.firebasestorage.app',
    androidClientId: '168903104893-dbitr4rbdch09ni3st6ngmmkrteie8d4.apps.googleusercontent.com',
    iosClientId: '168903104893-bf65bc4brrth6tk9d6i32d7e4e0vshj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDietAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCInfrJGZc5t9uQ9yV9S3MnjHvZdoOU4zU',
    appId: '1:168903104893:ios:e0009959c9e332487ed414',
    messagingSenderId: '168903104893',
    projectId: 'dietaiapp-268dd',
    storageBucket: 'dietaiapp-268dd.firebasestorage.app',
    androidClientId: '168903104893-dbitr4rbdch09ni3st6ngmmkrteie8d4.apps.googleusercontent.com',
    iosClientId: '168903104893-bf65bc4brrth6tk9d6i32d7e4e0vshj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDietAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRycVf3kYqyZt_VMiWDkGXJss_ypYj-GY',
    appId: '1:168903104893:web:dc58c467666e8fad7ed414',
    messagingSenderId: '168903104893',
    projectId: 'dietaiapp-268dd',
    authDomain: 'dietaiapp-268dd.firebaseapp.com',
    storageBucket: 'dietaiapp-268dd.firebasestorage.app',
    measurementId: 'G-Y22HBH7S88',
  );
}
